# Generated by Django 6.0 on 2026-01-04 20:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('music', '0003_userprofile_avatar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='comments_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='track',
            name='extracted_album',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='track',
            name='extracted_artist',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='track',
            name='extracted_genre',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='track',
            name='extracted_title',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='track',
            name='extracted_track_number',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='track',
            name='extracted_year',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='track',
            name='has_site_branding',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='track',
            name='is_optimized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='track',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='track',
            name='likes_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='track',
            name='optimized_file',
            field=models.FileField(blank=True, null=True, upload_to='tracks/optimized/'),
        ),
        migrations.AddField(
            model_name='track',
            name='original_filename',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='track',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('social', 'Social'), ('milestone', 'Milestone'), ('system', 'System'), ('like', 'Like'), ('comment', 'Comment'), ('share', 'Share'), ('follow', 'Follow'), ('mention', 'Mention')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_object_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='music_notif_user_id_b8e17b_idx'), models.Index(fields=['user', 'is_read'], name='music_notif_user_id_a38187_idx'), models.Index(fields=['type', '-created_at'], name='music_notif_type_9a2b1d_idx')],
            },
        ),
    ]
